// Simple Icons CDN for real brand logos (white variant for dark theme)
const SI = (slug) => `https://cdn.simpleicons.org/${slug}/white`;

export const LOGO_URLS = {
  'google-workspace': SI('google'),
  'google-sheets': SI('googlesheets'),
  'gmail': SI('gmail'),
  'notion': SI('notion'),
  'voice-dump': null, // custom icon, no brand logo
  'obsidian': SI('obsidian'),
  'slack': SI('slack'),
  'github': SI('github'),
  'trello': SI('trello'),
  'todoist': SI('todoist'),
  'linear': SI('linear'),
  'airtable': SI('airtable'),
  'discord': SI('discord'),
  'telegram': SI('telegram'),
  'google-calendar': SI('googlecalendar'),
  'spotify': SI('spotify'),
  'twitter-x': SI('x'),
  'instagram': SI('instagram'),
  'zapier': SI('zapier'),
  'make': SI('make'),
  'jira': SI('jira'),
  'asana': SI('asana'),
  'figma': SI('figma'),
  'dropbox': SI('dropbox'),
  'onedrive': SI('microsoftonedrive'),
};

export function getLogoUrl(appId) {
  return LOGO_URLS[appId] || null;
}

export const APP_CATALOG = [
  // ACTIVE
  {
    id: 'google-workspace',
    name: 'Google Workspace',
    description: 'Gmail, Calendar, Drive, Sheets, Docs - all in one',
    category: 'productivity',
    status: 'active',
    connect_url: 'https://workspace.google.com/',
    icon_color: '#4285F4',
    icon_letter: 'G',
    auth_type: 'gws',
    token_help: 'Connected via Google Workspace CLI. Re-run gws auth to refresh.',
  },
  {
    id: 'google-sheets',
    name: 'Google Sheets',
    description: 'Spreadsheet data management and analysis',
    category: 'productivity',
    status: 'active',
    connect_url: 'https://docs.google.com/spreadsheets/',
    icon_color: '#0F9D58',
    icon_letter: 'S',
    auth_type: 'gws',
    token_help: 'Connected via Google Workspace CLI.',
  },
  {
    id: 'gmail',
    name: 'Gmail',
    description: 'Send, receive, and manage emails',
    category: 'communication',
    status: 'active',
    connect_url: 'https://mail.google.com/',
    icon_color: '#EA4335',
    icon_letter: 'M',
    auth_type: 'gws',
    token_help: 'Connected via Google Workspace CLI.',
  },
  {
    id: 'notion',
    name: 'Notion',
    description: 'All-in-one workspace for notes, tasks, and databases',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://www.notion.so/my-integrations',
    icon_color: '#000000',
    icon_letter: 'N',
    auth_type: 'oauth',
    oauth_start_url: '/api/auth/notion/start',
    token_help: 'Click Connect to sign in with your Notion account.',
  },
  {
    id: 'voice-dump',
    name: 'Voice Dump',
    description: 'Transcribe and process voice messages',
    category: 'ai',
    status: 'active',
    connect_url: '',
    icon_color: '#8B5CF6',
    icon_letter: 'V',
    auth_type: 'none',
    token_help: 'Built-in feature, no configuration needed.',
  },
  // AVAILABLE
  {
    id: 'obsidian',
    name: 'Obsidian',
    description: 'Local-first knowledge base and note-taking',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://obsidian.md/',
    icon_color: '#7C3AED',
    icon_letter: 'O',
    auth_type: 'local',
    token_help: 'Local-only app. Install the Obsidian plugin to sync.',
  },
  {
    id: 'slack',
    name: 'Slack',
    description: 'Team messaging and workflow automation',
    category: 'communication',
    status: 'available',
    connect_url: 'https://api.slack.com/apps',
    icon_color: '#4A154B',
    icon_letter: 'Sl',
    auth_type: 'oauth',
    token_help: 'Click Connect to authorize via Slack OAuth.',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Code repositories, issues, and pull requests',
    category: 'developer',
    status: 'available',
    connect_url: 'https://github.com/settings/tokens',
    icon_color: '#181717',
    icon_letter: 'Gh',
    auth_type: 'token',
    token_help: 'Go to github.com/settings/tokens, create a Fine-grained token with repo access, and paste it here.',
  },
  {
    id: 'trello',
    name: 'Trello',
    description: 'Visual project boards and task management',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://trello.com/power-ups/admin',
    icon_color: '#0052CC',
    icon_letter: 'Tr',
    auth_type: 'token',
    token_help: 'Get your API key from trello.com/power-ups/admin, then generate a token.',
  },
  {
    id: 'todoist',
    name: 'Todoist',
    description: 'Task management and to-do lists',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://todoist.com/app/settings/integrations',
    icon_color: '#E44332',
    icon_letter: 'Td',
    auth_type: 'token',
    token_help: 'Go to todoist.com/app/settings/integrations and copy your API token.',
  },
  {
    id: 'linear',
    name: 'Linear',
    description: 'Modern issue tracking for software teams',
    category: 'developer',
    status: 'available',
    connect_url: 'https://linear.app/settings/api',
    icon_color: '#5E6AD2',
    icon_letter: 'Li',
    auth_type: 'token',
    token_help: 'Go to linear.app/settings/api and create a Personal API key.',
  },
  {
    id: 'airtable',
    name: 'Airtable',
    description: 'Flexible database and spreadsheet hybrid',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://airtable.com/create/tokens',
    icon_color: '#18BFFF',
    icon_letter: 'At',
    auth_type: 'token',
    token_help: 'Go to airtable.com/create/tokens and create a Personal Access Token.',
  },
  {
    id: 'discord',
    name: 'Discord',
    description: 'Community chat and voice channels',
    category: 'communication',
    status: 'available',
    connect_url: 'https://discord.com/developers/applications',
    icon_color: '#5865F2',
    icon_letter: 'Dc',
    auth_type: 'oauth',
    token_help: 'Click Connect to authorize via Discord OAuth.',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    description: 'Cloud-based messaging with bot support',
    category: 'communication',
    status: 'available',
    connect_url: 'https://core.telegram.org/bots#botfather',
    icon_color: '#26A5E4',
    icon_letter: 'Tg',
    auth_type: 'token',
    token_help: 'Message @BotFather on Telegram, create a bot, and paste the bot token here.',
  },
  {
    id: 'google-calendar',
    name: 'Google Calendar',
    description: 'Standalone calendar scheduling and events',
    category: 'productivity',
    status: 'available',
    connect_url: 'https://calendar.google.com/',
    icon_color: '#4285F4',
    icon_letter: 'Ca',
    auth_type: 'oauth',
    token_help: 'Click Connect to authorize via Google OAuth.',
  },
  // COMING SOON
  {
    id: 'spotify',
    name: 'Spotify',
    description: 'Music streaming and playlist management',
    category: 'ai',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#1DB954',
    icon_letter: 'Sp',
  },
  {
    id: 'twitter-x',
    name: 'Twitter / X',
    description: 'Social media posts and monitoring',
    category: 'communication',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#1DA1F2',
    icon_letter: 'X',
  },
  {
    id: 'instagram',
    name: 'Instagram',
    description: 'Photo and story sharing platform',
    category: 'communication',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#E4405F',
    icon_letter: 'Ig',
  },
  {
    id: 'zapier',
    name: 'Zapier',
    description: 'Connect apps and automate workflows',
    category: 'automation',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#FF4F00',
    icon_letter: 'Za',
  },
  {
    id: 'make',
    name: 'Make',
    description: 'Visual automation and integration platform',
    category: 'automation',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#6D00CC',
    icon_letter: 'Mk',
  },
  {
    id: 'jira',
    name: 'Jira',
    description: 'Agile project management and bug tracking',
    category: 'developer',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#0052CC',
    icon_letter: 'Ji',
  },
  {
    id: 'asana',
    name: 'Asana',
    description: 'Work management and team coordination',
    category: 'productivity',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#F06A6A',
    icon_letter: 'As',
  },
  {
    id: 'figma',
    name: 'Figma',
    description: 'Collaborative design and prototyping',
    category: 'developer',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#F24E1E',
    icon_letter: 'Fi',
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    description: 'Cloud file storage and sharing',
    category: 'storage',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#0061FF',
    icon_letter: 'Db',
  },
  {
    id: 'onedrive',
    name: 'OneDrive',
    description: 'Microsoft cloud storage and sync',
    category: 'storage',
    status: 'coming_soon',
    connect_url: '',
    auth_type: 'coming_soon',
    icon_color: '#0078D4',
    icon_letter: 'Od',
  },
];

export const APP_CATEGORIES = [
  { id: 'all', label: 'All Apps' },
  { id: 'productivity', label: 'Productivity' },
  { id: 'communication', label: 'Communication' },
  { id: 'developer', label: 'Developer' },
  { id: 'automation', label: 'Automation' },
  { id: 'storage', label: 'Storage' },
  { id: 'ai', label: 'AI' },
];

export function getAppsByCategory(catalog, categoryId) {
  if (categoryId === 'all') return catalog;
  return catalog.filter((app) => app.category === categoryId);
}

export function getAppsByStatus(catalog, status) {
  return catalog.filter((app) => app.status === status);
}
