"""Booking Proactive Engine — fires independently of the LLM conversation loop.

Aristotle's efficient cause: what moves the system forward without being asked.

Two responsibilities:
  1. TTL expiry: if contact doesn't reply within ttl_hours → expire booking
  2. Pre-meeting brief: 60 minutes before confirmed meeting → generate + send brief

Both run on a ticker loop (60-second intervals). Neither requires an LLM
message to trigger — they observe state and act on schedule.

The brief is generated by calling the AI gateway directly (not via the
conversation loop) with a prompt assembled from BriefContext.
"""

from __future__ import annotations

import asyncio
import json
import os
from datetime import datetime, timedelta, timezone
from typing import Any

try:
    import httpx
except ImportError:
    httpx = None

from .models import BookingRecord, BookingState, BookingIntent
from .context import ContextAggregator, format_brief_context


BRIEF_LEAD_MINUTES = 60   # Send brief this many minutes before meeting
TICK_INTERVAL_SECONDS = 60


class BookingProactiveEngine:
    """Cron-like engine that fires TTL expiry and pre-meeting briefs.

    Completely independent of the LLM conversation loop.
    Observes BookingEngine state. Acts on schedule.
    """

    def __init__(
        self,
        engine,                    # BookingEngine
        context_aggregator: ContextAggregator,
        config: dict,
        channel=None,              # WhatsAppChannel — for sending brief
        http_client=None,          # httpx.AsyncClient — for AI gateway
    ):
        self._engine = engine
        self._ctx = context_aggregator
        self._config = config
        self._channel = channel
        self._http = http_client
        self._running = False
        self._task: asyncio.Task | None = None

    def start(self) -> None:
        """Start the background tick loop."""
        if not self._running:
            self._running = True
            self._task = asyncio.create_task(self._loop())
            print("[booking/proactive] Engine started")

    def stop(self) -> None:
        """Stop the background tick loop."""
        self._running = False
        if self._task and not self._task.done():
            self._task.cancel()

    async def _loop(self) -> None:
        """Main tick loop. Runs every TICK_INTERVAL_SECONDS."""
        while self._running:
            try:
                await self._tick()
            except Exception as e:
                print(f"[booking/proactive] Tick error: {e}")
            await asyncio.sleep(TICK_INTERVAL_SECONDS)

    async def _tick(self) -> None:
        """One tick: check TTLs + check for upcoming meetings."""
        now = datetime.now(tz=timezone.utc)
        await asyncio.gather(
            self._check_ttl_expirations(now),
            self._check_upcoming_meetings(now),
            return_exceptions=True,
        )

    # ── TTL expiry ──

    async def _check_ttl_expirations(self, now: datetime) -> None:
        """Expire bookings where contact hasn't replied within ttl_hours."""
        pending = self._engine.get_awaiting_contact_reply()
        for booking in pending:
            try:
                created = datetime.fromisoformat(booking.created_at)
                ttl = timedelta(hours=booking.ttl_hours)
                if now - created > ttl:
                    print(f"[booking/proactive] Expiring {booking.id} (TTL {booking.ttl_hours}h)")
                    await self._engine.expire(booking)
            except Exception as e:
                print(f"[booking/proactive] TTL check error for {booking.id}: {e}")

    # ── Pre-meeting brief ──

    async def _check_upcoming_meetings(self, now: datetime) -> None:
        """Send brief for meetings that start within BRIEF_LEAD_MINUTES."""
        confirmed = self._engine.get_confirmed_upcoming()
        for booking in confirmed:
            try:
                if not booking.contact_choice:
                    continue

                meeting_time_str = booking.contact_choice.get("start", "")
                if not meeting_time_str:
                    continue

                meeting_time = datetime.fromisoformat(meeting_time_str)
                # Normalize to UTC
                if meeting_time.tzinfo is None:
                    meeting_time = meeting_time.replace(tzinfo=timezone.utc)

                delta = meeting_time - now
                delta_minutes = delta.total_seconds() / 60

                if 0 < delta_minutes <= BRIEF_LEAD_MINUTES:
                    print(f"[booking/proactive] Sending brief for {booking.id} "
                          f"({delta_minutes:.0f}min before meeting)")
                    await self._send_brief(booking)

            except Exception as e:
                print(f"[booking/proactive] Brief check error for {booking.id}: {e}")

    async def _send_brief(self, booking: BookingRecord) -> None:
        """Generate and send pre-meeting brief to owner."""
        # Assemble context
        ctx = await self._ctx.for_pre_meeting_brief(booking)
        brief_prompt = format_brief_context(ctx)

        # Generate brief via AI gateway (not via conversation loop)
        brief_text = await self._generate_brief(brief_prompt)
        if not brief_text:
            print(f"[booking/proactive] Brief generation failed for {booking.id}")
            return

        # Send to owner via WhatsApp
        owner_number = self._config.get("escalation_notify_number") or \
                       self._config.get("admin_number", "")
        if owner_number and self._channel:
            owner_jid = f"{owner_number}@s.whatsapp.net"
            header = f"*Pre-meeting brief [{booking.id}]*\n\n"
            try:
                await self._channel.send_text(owner_jid, header + brief_text)
                print(f"[booking/proactive] Brief sent for {booking.id}")
            except Exception as e:
                print(f"[booking/proactive] Failed to send brief: {e}")
                return

        # Mark brief sent + advance to COMPLETE
        booking.brief_sent = True
        await self._engine.mark_complete(booking)

    async def _generate_brief(self, prompt: str) -> str:
        """Call AI gateway to generate the brief text."""
        if not self._http:
            return ""

        gateway_url = self._config.get("ai_gateway_url", "https://ai-gateway.happycapy.ai/api/v1")
        model = self._config.get("ai_model", "anthropic/claude-haiku-4.5")
        api_key = os.environ.get("AI_GATEWAY_API_KEY", "")

        if not api_key:
            return ""

        try:
            payload = {
                "model": model,
                "messages": [{"role": "user", "content": prompt}],
                "max_tokens": 600,
            }
            resp = await self._http.post(
                f"{gateway_url}/chat/completions",
                json=payload,
                headers={"Authorization": f"Bearer {api_key}"},
                timeout=30,
            )
            if resp.status_code == 200:
                data = resp.json()
                return data["choices"][0]["message"]["content"].strip()
        except Exception as e:
            print(f"[booking/proactive] AI gateway error: {e}")
        return ""

    # ── External trigger: on_state_change ──

    async def on_state_change(self, booking: BookingRecord, new_state: BookingState) -> None:
        """Called by engine event bus when any booking changes state.

        When a booking is confirmed, schedule the brief time in the record
        so the tick loop knows when to fire.
        """
        if new_state == BookingState.BOOKING_CONFIRMED and booking.contact_choice:
            meeting_time_str = booking.contact_choice.get("start", "")
            if meeting_time_str:
                try:
                    meeting_time = datetime.fromisoformat(meeting_time_str)
                    brief_time = meeting_time - timedelta(minutes=BRIEF_LEAD_MINUTES)
                    self._engine.set_brief_scheduled(
                        booking.id, brief_time.isoformat()
                    )
                    print(
                        f"[booking/proactive] Brief scheduled for {booking.id} "
                        f"at {brief_time.isoformat()}"
                    )
                except Exception as e:
                    print(f"[booking/proactive] Failed to schedule brief: {e}")
